language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
notifications:
  email:       #false OLD SETTING, TESTING CODE BELOW
    recipients:
      - jeff.d.camacho@gmail.com
      - jeff@jeffcamacho.com
    on_success: never # default: change
    on_failure: always # default: always

