# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data, Tactics, Knowledge
email: jeff.d.camacho@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is the professional site for Jeff Camacho. He is an analyist,
  engineer, writer, and fitness enthusiast.
timezone: America/Chicago
logo: "/assets/images/REVERSE ENGINEERING.png"
twitter_username: jc1821
github_username: jeff-mos-def
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-161040672-1"
    anonymize_ip         : false
bing_site_verification: "0FC3FD70512616B052E755A56F8952D"

author:
  name   : "Jeff Camacho"
  avatar : "/assets/images/Jeff.jpg"
  bio    : "Analyist, engineer, and crossfitter.
            Passion for gadgets and a flair for problem solving."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-link"
      url: "mailto:jeff.d.camacho@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jc1821"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeff-mos-def"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jeff_mos_def"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jeff-camacho/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jc1821"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeff-mos-def/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/jeff_mos_def/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jeff-camacho/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
